name: Bacon2022_2022GC010564
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.5.1
  - numpy=1.21.5
  - obspy=1.2.2
  - pandas=1.4.1
  - pygmt=0.6.0
  - pyproj=3.3.0
  - python=3.8.13
  - scipy=1.8.0
